### ISSUE TITLE
mu register error

### ISSUE THREAD

**Issue by AlexGreg** [fabioz/mu-repo#25]
mu installed via pip command..never worked
```
Traceback (most recent call last):
  File "/usr/local/bin/mu", line 9, in <module>
    load_entry_point('mu-repo==1.3.0', 'console_scripts', 'mu')()
  File "/usr/local/lib/python2.7/dist-packages/mu_repo/__init__.py", line 312, in main_entry_point
    main()
  File "/usr/local/lib/python2.7/dist-packages/mu_repo/__init__.py", line 301, in main
    return Run(Params(config, args, config_file))
  File "/usr/local/lib/python2.7/dist-packages/mu_repo/action_register.py", line 66, in Run
    with open(config_file, 'w') as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Thanks!

**Comment by AlexGreg** [comment]
tried even with python3:
```
Traceback (most recent call last):
  File "/usr/local/bin/mu", line 9, in <module>
    load_entry_point('mu-repo==1.3.0', 'console_scripts', 'mu')()
  File "/usr/local/lib/python3.5/dist-packages/mu_repo/__init__.py", line 312, in main_entry_point
    main()
  File "/usr/local/lib/python3.5/dist-packages/mu_repo/__init__.py", line 301, in main
    return Run(Params(config, args, config_file))
  File "/usr/local/lib/python3.5/dist-packages/mu_repo/action_register.py", line 66, in Run
    with open(config_file, 'w') as f:
TypeError: invalid file: None
```

**Comment by AlexGreg** [comment]
fixed the problem by `touch`ing the .mu_repo file

**Comment by fabioz** [comment]
It seems this broke in the last version when the feature to execute mu on subdirectories was added (and it only happened on new mu-repo installations, while .mu_repo wasn't created, which is why it took so long for it to appear and touching the .mu_repo file made it work).

**Comment by AlexGreg** [comment]
Great! Keep up the good job! :+1:
